internal/source: rename variables that collided with builtins (revive)
"cap" is now a builtin:

    internal/source/source_test.go:50:2: redefines-builtin-id: redefinition of the built-in function cap (revive)
        cap := &capture{}
        ^
    internal/source/source_test.go:73:2: redefines-builtin-id: redefinition of the built-in function cap (revive)
        cap := &capture{}
        ^
    internal/source/source_test.go:86:2: redefines-builtin-id: redefinition of the built-in function cap (revive)
        cap := &capture{}
        ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>